[toolchain]
channel = "1.97.1" # NOTE: Always use full version numbers (`x.y.z` instead of `x.y`)
profile = "default"
components = ["rust-src"]
targets = [
    "armv7-unknown-linux-musleabihf",
    "armv7-unknown-linux-gnueabihf",
    "arm-unknown-linux-musleabi",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "wasm32-unknown-unknown",
    "riscv32imc-unknown-none-elf",
]
